apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitem-deployment
  labels:
    app: orderitem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderitem
  template:
    metadata:
      labels:
        app: orderitem
    spec:
      containers:
      - name: orderitem
        image: myazurecontainerregistrycraa.azurecr.io/orderitemimageaas:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: orderitemsecret
---
apiVersion: v1
kind: Service
metadata:
  name: orderitem-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: orderitem